# Generated by Django 5.1.7 on 2025-03-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_status_book_availability_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Checked Out', 'Checked Out'), ('Reserved', 'Reserved')], default='Available', max_length=50),
        ),
    ]
